version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Aa123456@
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
        - "5433:5432"
    volumes:
      - postgres_catalog:/va@r/lib/postgresql/data/     